version: '3.7'
x-environment:
  &dbenvs
  MYSQL_USER: "noderestapi"
  MYSQL_PASSWORD: "noderestapi"
  MYSQL_DATABASE: "noderestapi"
services:
  noderestapi:
    build: .
    environment:
      <<: *dbenvs
      NODE_ENV: 'dev'
      # sitedb exposed port
      DB_PORT: 33060
    ports:
      - "8080:3000"
      - "8081:3001"
    volumes:
      - .:/app/src
    command: npm start
    links:
      - "sitedb:database"
    restart: on-failure
  sitedb:
    image: mysql/mysql-server:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "32770:3306"
      - "32769:33060"
    environment:
      <<: *dbenvs
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
