version: '3'
services:
  server:
    build: .
    environment:
      NODE_ENV: 'dockerdev'
    ports:
      - "8080:3000"
      - "8081:3001"
    volumes:
      - ./Controllers:/app/src/Controllers
      - ./Database:/app/src/Database
      - ./Entities:/app/src/Entities
      - ./Router:/app/src/Router
      - ./Server:/app/src/Server
      - ./NodeAnnotations:/app/src/NodeAnnotations